project:
  type: website
  output-dir: docs

website:
  title: "Vinicius Bastazini"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd
      - people.qmd
      - projects.qmd
      - professional.qmd
      - media.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true